### PR TITLE
Use the field min and max values to determine the years range

### PR DESCRIPTION
**Pull request by mpeeters**
Use the min or max value if they are defined on the zope.schema field instead of the default years range (-10 / +10)

### CODE REVIEW

**Comment by davisagli** [comment]
Probably because Plone core now uses date widgets in plone.app.z3cform (based on the pickadate pattern in mockup)

**Comment by bsuttor** [comment]
Ok thanks,
So only tests on 4.3 and 5.0 are useful for this package ?
And in this case, they are green, we can merge this PR

**Comment by thet** [comment]
LGTM

**Comment by mpeeters** [comment]
Thanks

**Pull request merged**
